### ISSUE TITLE
Remove CoSE-Bilkent layout

### ISSUE THREAD

**Issue by Arnedeklerk** [Rothamsted/knetmaps.js#40]
CoSE-Bilkent layout no longer works. Code relating to it should be removed, along with the dropdown list.

**Comment by marco-brandizi** [comment]
This is a Knetmaps issue. I still don't get if we should use Knetminer issues for everything (helps us with having everything in a single place, but needs at least that the relevant repo is mentioned in the labels) or work per-repository (helps others to see issues related to a repo close to it).

**Comment by Arnedeklerk** [comment]
Whoops. You're right and just an accident on my part. We can keep working per repo because the kanban integrates on an organisational level.

**Comment by marco-brandizi** [comment]
@lawal-olaotan, I've done it. I still had to push a proper release, so it was worth to add this minimal change while doing that.
