### ISSUE TITLE
Save/export networks

### ISSUE THREAD

**Issue by AjitPS** [Rothamsted/knetmaps.js#5]
A frequently requested feature:

- [ ] Allow users to **save** networks and **reload** later. 
1. Note (by @AjitPS): we are looking into a feature to “**_export_**” networks to NDEx via their API and **_import_** KnetMaps networks in from NDEx as well.

**Comment by AjitPS** [comment]
annotate networks and save/share/publish (login?)

**Comment by AjitPS** [comment]
could do either:
- press export and generate a `blob` with the `json`, save locally on filesytsem or on a small `sql` database, i.e., 1 blob each time user exports a network
- have a login system (relational db-backed) and have a user dashboard with all their saved networks (**advanced**)

**Comment by KeywanHP** [comment]
Release 5.6: knetworks can be saved to users workspace accounts (knetspace) and downloaded as json.
