### ISSUE TITLE
Add and hide nodes using the legend

### ISSUE THREAD

**Issue by KeywanHP** [Rothamsted/knetmaps.js#8]
- [x] Add and hide nodes of a specific type using legend icons
- [x] Icons that return 0 nodes should be deactivated (faded)
- [x] Numbers next to icons should be in % indicating what percentage of a specific concept type is shown (3/10) or how many nodes will be added if the icon is pressed
- [x] Once an icon is pressed, it should update it's own status and that of all other icons
- [x] Needs to work equally with adding and hiding nodes

**Comment by josephhearnshaw** [comment]
Please review https://github.com/Rothamsted/knetminer/pull/406 regarding modifications with the above features in mind - what do you think?

**Comment by josephhearnshaw** [comment]
Currently, behaviour is as expected, though error handling requires attention. When the correct nodes have been added, the error message should be cleared. I'll resolve this behaviour as soon as possible. 

It may also make more sense to make the total number of nodes be in bold, so it's clearer to the user.

**Comment by josephhearnshaw** [comment]
This issue can be closed.

**Comment by AjitPS** [comment]
thanks @josephhearnshaw  for finishing this
